[package]
name = "repo-sync"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.14", features = ["derive"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
job_scheduler_ng = "*"

[profile.release]
lto = true
strip = true
